[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AleksandrGrafin", email = "Aleksandr.Sh1991@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "prompt>=0.4.1",
]

[project.scripts]
python-project-49 = "python_project_49:main"
brain-games = "brain_games.scripts.brain_games:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["brain_games"]

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]

